
#run macro for local testing

#detectors and components




# Initialize kernel
/run/initialize


#Caryn added
 /process/activate SynchrotronRadiation
#
# inactivate other processes to make SynchrotronRadiation more visible
#/process/inactivate msc
#/process/inactivate eIoni
#/process/inactivate eBrem
#/process/inactivate annihil
#/process/inactivate phot
#/process/inactivate compt
#/process/inactivate conv
#/process/inactivate Rayl


/run/beamOn 10

